name: e_wallet
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_svg: 1.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/svg/
  uses-material-design: true

